source 'https://rubygems.org'


gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

gem 'jquery-turbolinks'
gem "haml-rails", '~> 0.9.0'
gem 'devise', '~> 3.5.2'
gem 'simple_form', '~> 3.2.0'

gem 'puma'
group :development, :test do
   # Call 'byebug' anywhere in the code to stop execution and get a debugger console
   gem 'byebug'
   gem 'awesome_print', require:'ap'
   gem 'hirb', '~> 0.7.3'

   # Access an IRB console on exception pages or by using <%= console %> in views
   gem 'web-console', '~> 2.0'
   gem 'meta_request'
   gem 'better_errors'
   gem 'annotate'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
